# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "f541255ab6a57d3e86e82f54addd3e85"
name = "Discounts + Reviews (New)"
application_url = "https://discounts-ai-reviews.onrender.com"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-10"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_discounts,read_themes,write_themes,write_products,write_files,write_app_proxy"

[auth]
redirect_urls = [ "https://discounts-ai-reviews.onrender.com/api/auth" ]

[app_proxy]
url = "/my-app-proxy"
prefix = "apps"
subpath = "my-custom-path"